imageProcessing:
  historySize: 100

  server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: "/"

spring:
  application:
    name: "image-processing-service"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Enable actuator endpoints:
#  - health: used by LivenessProbe and ReadinessProbe to mark this app as running
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    au.com.sydneywater.imageprocessor: INFO

logging.pattern.console: "%clr(%d{YYYY-MM-dd E HH:mm:ss.SSS}){faint} %clr(%-5p) %clr(${PID}){faint} %clr([%8.15t]){faint} %clr(%c{1.}:%L){cyan} %clr(:){red} %clr(%m){faint}%n"

